### ISSUE TITLE
[BUG]:  Incorrect Calculation of Current Iteration in SCSO Algorithm ( At line number 78 in SCSO.py file )

### ISSUE THREAD

**Issue by godharakesh** [thieu1995/.github#3]
### Description of the bug

In the file SCSO.py, there is an error in the calculation of the current iteration in the evolve method of the OriginalSCSO class. The line t = self.epoch + 1 should be replaced with t = epoch + 1 to correctly represent the current iteration according to the formula. Currently, the variable t is assigned the value of the total number of iterations (self.epoch) instead of the current iteration (epoch). This issue affects the behavior of the algorithm and may lead to incorrect results.

<img width="224" alt="image" src="https://github.com/thieu1995/.github/assets/75328586/66c71c89-f062-4bda-9e1c-ffcdcc54ea87"> \
https://link.springer.com/article/10.1007/s00366-022-01604-x

### Steps To Reproduce

Go to https://github.com/thieu1995/mealpy/blob/2ec7436fbf045b9af544d4f6f25d4b7ef27ab286/mealpy/swarm_based/SCSO.py#LL78C27-L78C27

**Comment by thieu1995** [comment]
@godharakesh,

Thanks for pointing out this bug. I have fixed in new alpha version. 
But why did you create an issue here tho? 
I will close this one. Please go to Mealpy repository and check it out.
